name: Publish Package Auth Client Spring Boot Starter

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'package version'
        type: string
        required: true

env:
  REPO_OPENSRCDEVELOP_PASSWORD: ${{ secrets.REPO_OPENSRCDEVELOP_PASSWORD }}

jobs:
  publish-jar:
    name: Publish Jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Version
        run: |
          sed -i 's/version=.*/version=${{ inputs.version }}/g' ./auth-client-spring-boot-starter/gradle.properties

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0


      - name: Build With Gradle Wrapper
        run: |
          chmod +x ./gradlew
          ./gradlew -x test auth-client-spring-boot-starter:build

      - name: Publish to Maven repository
        run: |
          ./gradlew auth-client-spring-boot-starter:publish